# Generated by Django 2.0.5 on 2018-05-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userfeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfeeditem',
            old_name='user_profile',
            new_name='user',
        ),
    ]
