# Generated by Django 2.0.5 on 2018-05-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180505_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfeeditem',
            old_name='user',
            new_name='user_profile',
        ),
    ]
